server:
    port: 8080

spring:
    profiles: dev
    
    datasource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        url: jdbc:postgresql:mlds
        databaseName: mlds
        serverName: localhost
        username: mlds
        password: password

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: POSTGRESQL
        show_sql: true
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.search.default.directory_provider: ram
# for debugging            
#            hibernate.search.default.directory_provider: filesystem
#            hibernate.search.default.indexBase: ./target/lucene


    mail:
        baseUrl: http://localhost:8080
        from: mlds@mailinator.com
        host: mail.intware.com
        port: 25
        user:
        password:
        protocol: smtp
        tls: false
        auth: false

    thymeleaf:
        mode: XHTML
        cache: false

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 16M

# You can add as many as folders to watch
# You just need to add a dash + the directory to watch
hotReload:
    enabled: true
    package:
      project: ca.intelliware.ihtsdo.mlds
      domain: ca.intelliware.ihtsdo.mlds.domain
      restdto: ca.intelliware.ihtsdo.mlds.web.rest.dto
    liquibase:
      defaultCatalogName: 
      defaultSchema: public
      excludeTables: 
    watchdir:
      - target/classes
