spring:
    profiles: dev
    
    jpa:
        properties:
# for debugging            
#            hibernate.search.default.directory_provider: filesystem
            hibernate.search.default.indexBase: ./target/lucene

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 16M

# You can add as many as folders to watch
# You just need to add a dash + the directory to watch
hotReload:
    enabled: true
    package:
      project: ca.intelliware.ihtsdo.mlds
      domain: ca.intelliware.ihtsdo.mlds.domain
      restdto: ca.intelliware.ihtsdo.mlds.web.rest.dto
    liquibase:
      defaultCatalogName: 
      defaultSchema: public
      excludeTables: 
    watchdir:
      - target/classes
