package ca.intelliware.ihtsdo.mlds.domain;

public enum OrganizationType {
	PUBLIC_HEALTH_ORGANIZATION,
	PRIVATE_HEALTH_ORGANIZATION,
	RESEARCH_AND_DEVELOPMENT_ORGANIZATION,
	HEALTHERCARE_APPLICATION_DEVELOPER,
	HEALTHERCARE_APPLICATION_PROVIDER,
	GENERAL_PRACTITIONER_PRACTICE,
	EDUCATIONAL_INSTITUTE,
	OTHER;
}
